### ISSUE TITLE
Can you had a keybinding  ?

### ISSUE THREAD

**Issue by shiroling** [Pieloaf/BetterDiscordPlugins#3]
Hello I'm using arch linux and I3 has desktop env, your plugin works really well.
And i was just thinking that it would be a great upgrade if you add a keybind to toggle the pannel view.
Also did you know one plugin that make the same thing with the right pannel ?

Thanks for your plugin, it's a great one !

**Comment by Pieloaf** [comment]
Sure, I can take a look at it, although I'm a lil busy at the moment, I'll take a look when I get the chance.

Glad you like the plugin :))

**Comment by Pieloaf** [comment]
@shiroling added alt+h as a keybind, I havent had time to look at api docs to add a settings menu but you can change the keybind in the file pretty easily, lines [57 and 58](https://github.com/Pieloaf/BetterDiscordPlugins/blob/main/HideSidebar.plugin.js#L57-L58)
